.myglobals:
  tags:
    - k8s

image: maven:3-openjdk-11

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

include:
  - project: 'kgroup/dependabot-standalone'
    file: '.gitlab-ci.yml'

cache:
  paths:
    - .m2/repository/
    - target/

build:
  extends:
    - .myglobals
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  extends:
    - .myglobals
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

sonarqube-check:
  extends:
    - .myglobals
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - git fetch --unshallow --all
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop

prepare_job:
  extends:
    - .myglobals
  stage: build
  only:
    variables:
      - '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null'
  script:
    - export TAGNOW=$CI_COMMIT_TAG
    - export TAGPREV=$(git describe --abbrev=0 $TAGNOW^)
    - export COMMITPREV=$(git rev-list -n 1 $TAGPREV)
    - echo "TAG=$(git describe --abbrev=0)" >> variables.env
    - echo "COMMITNOW=$CI_COMMIT_SHA" >> variables.env
    - echo "COMMITPREV=$COMMITPREV" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

release_job:
  extends:
    - .myglobals
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  only:
    variables:
      - '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null'
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli'
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'

jdoc:
  extends:
    - .myglobals
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS site
  artifacts:
    paths:
      - target/site/

pages:
  extends:
    - .myglobals
  stage: deploy
  image: alpine
  before_script:
    - mkdir public
  script:
    - cp -a target/site/* public/
  artifacts:
    paths:
      - public
