stages:
  - build
  - test
  - visualize
  - deploy

.myglobals:
  interruptible: true
  tags:
    - $RUNNERTAG

.whenNormal:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"

.whenTagged:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_TAG != null

image: maven:3-openjdk-11

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DEPENDABOT_IMAGE: docker.io/$DEPENDABOTIMAGE

.dependabot-gitlab:
  tags:
    - $RUNNERTAG
  image:
    name: $DEPENDABOT_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    RAILS_ENV: production
    PACKAGE_MANAGER: maven
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__STANDALONE: "true"
    PROJECT_PATH: stackedcrypto/JaStaCry
    DIRECTORY: /
  before_script:
    - echo "Version dependabot $DEPENDABOTIMAGE"
    - cd /home/dependabot/app
  script:
    - bundle exec rake "dependabot:update[$PROJECT_PATH,$PACKAGE_MANAGER,$DIRECTORY]"

cache:
  paths:
    - .m2/repository/
    - target/

dependabot:
  stage: test
  extends: .dependabot-gitlab
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

build:
  extends:
    - .myglobals
    - .whenNormal
  stage: build
  cache:
    policy: push
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

package:
  extends:
    - .myglobals
    - .whenNormal
  stage: build
  variables:
    RUNNER_GENERATE_ARTIFACTS_METADATA: "true"
  needs:
    - job: build
      artifacts: false
  before_script:
    - ls -l target/
  script:
    - mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true
  after_script:
    - ls -l target/
    - echo "JARJOB=$CI_JOB_ID" > pvariables.env
  artifacts:
    paths:
      - target/jastacry-*.jar
    reports:
      dotenv: pvariables.env

test:
  extends:
    - .myglobals
    - .whenNormal
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%'
  after_script:
    - rm target/surefire-reports/TEST-org.jastacry.test.AllTests.xml || true
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

bom:
  extends:
    - .myglobals
    - .whenNormal
  stage: test
  variables:
    DTRACK_URL: ${DTRACK_URL}
    DTRACK_API: ${DTRACK_API}
    DTRACK_NAME: "jastacry"
  script:
    - mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
  after_script:
    - 'export DTRACK_VERSION=$(cut -d ":" -f 6 <VERSION.cpe)'
    - echo "projectName=${DTRACK_NAME}"
    - echo "projectVersion=${DTRACK_VERSION}"
    - 'curl -X POST ${DTRACK_URL}api/v1/bom -H "Content-Type: multipart/form-data" -H "X-API-Key: ${DTRACK_API}" -F "autoCreate=true" -F "projectName=${DTRACK_NAME}" -F "projectVersion=${DTRACK_VERSION}" -F bom=@target/bom.json'
  allow_failure: true
  artifacts:
    paths:
      - target/bom.json

sonarqube-check:
  extends:
    - .myglobals
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#    GIT_FETCH_EXTRA_FLAGS: --unshallow
    GIT_DEPTH: 0 # avoid shallow clone to give sonar all the info it needs
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
#  before_script:
#    - git fetch --unshallow --all
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true

coverity:
  extends:
    - .myglobals
    - .whenNormal
  stage: test
  cache:
    key: coverity-$CI_COMMIT_REF_SLUG
    paths:
       - coverity_tool.tgz
  before_script:
    - mvn clean
    - wget -nc -q https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_TOKEN}&project=${COVERITY_PROJECT}" -O coverity_tool.tgz || true
    - ls -l coverity_tool.tgz
    - mkdir coverity-tool
    - tar xzf coverity_tool.tgz --strip-components=1 -C coverity-tool
    - export PATH="${CI_PROJECT_DIR}/coverity-tool/bin:$PATH"
    - 'export COVERITY_VERSION=$(cut -d ":" -f 6 <VERSION.cpe)'
  script:
    - cov-build --dir cov-int mvn $MAVEN_CLI_OPTS compile
    - tar czf /tmp/jastacry.tar.gz cov-int/
    - curl --form token=${COVERITY_TOKEN} --form email=${COVERITY_LOGIN} --form file=@/tmp/jastacry.tar.gz --form version="${COVERITY_VERSION}" --form description="${COVERITY_PROJECT}" https://scan.coverity.com/builds?project=${COVERITY_PROJECT}
  allow_failure: true
  artifacts:
    paths:
      - cov-int/

prepare_job:
  extends:
    - .myglobals
    - .whenTagged
  stage: build
  script:
    - export TAGNOW=$CI_COMMIT_TAG
    - export TAGPREV=$(git describe --abbrev=0 $TAGNOW^)
    - export COMMITPREV=$(git rev-list -n 1 $TAGPREV)
    - echo "TAG=$(git describe --abbrev=0)" >> variables.env
    - echo "COMMITNOW=$CI_COMMIT_SHA" >> variables.env
    - echo "COMMITPREV=$COMMITPREV" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

coverage-jdk11:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["test"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml

release_job:
  extends:
    - .myglobals
    - .whenTagged
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
    - job: package
      artifacts: true
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli'
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'compiled jar'
          url: 'https://gitlab.kretschmann.software/stackedcrypto/JaStaCry/-/jobs/${JARJOB}/artifacts/download'

jdoc:
  extends:
    - .myglobals
    - .whenNormal
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS site
  artifacts:
    paths:
      - target/site/

pages:
  extends:
    - .myglobals
    - .whenNormal
  stage: deploy
  image: alpine
  before_script:
    - mkdir public
  script:
    - cp -a target/site/* public/
  artifacts:
    paths:
      - public
