version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    rebase-strategy: auto
    auto-merge: true
    commit-message:
      prefix: "dependabot maven"
      include: "scope"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
