version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependabot maven"
      include: "scope"
    ignore:
      - dependency-name: "maven-surefire-plugin"
